/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diary.app.components;

import diary.Diary8Desktop;
import diary.app.components.resources.JuliusCrypter;
import java.awt.Color;
import java.io.File;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author Harsh
 */
public class LogItem extends JPanel {

    boolean isSelected = false;
    Color DEFAULT = Color.WHITE;
    Color DEFAULTTEXT = Color.BLACK;
    Color SELECTED = Color.BLACK;
    Color SELECTEDTEXT = Color.WHITE;
    Color OVER = new Color(220, 220, 220);
    Date DATE;
    String LogFile;
    String[] dayOfWeek = {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};

    /**
     * Creates new form DateItem
     */
    public LogItem() {
        initComponents();
    }

    public String getLogFile() {
        return LogFile;
    }

    public void setLog(String logFileName) {
        LogFile = logFileName;
        System.out.println(LogFile);
        String n = logFileName;
        if (n.contains(".logx")) {
            n = n.substring(0, n.lastIndexOf(".logx"));
        }
        String time = "";
        if (n.indexOf(".") != -1) {
            time = n.substring(0, n.indexOf("."));
        } else {
            time = n;
        }
        StringTokenizer st = new StringTokenizer(time, "-");
        String h = (st.nextToken());
        String m = (st.nextToken());
        String s = (st.nextToken());
        String title = n.substring(n.indexOf(".") + 1);
        title = new JuliusCrypter().perfectSquareCrypt(title);
        this.time.setText(h + ":" + m + ":" + s);
        this.title.setText(title);
    }

    public void setColors(Color fg, Color bg) {
        setBackground(bg);
        time.setForeground(fg);
        title.setForeground(fg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 55));
        setMinimumSize(new java.awt.Dimension(300, 55));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        time.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("00:00:00");

        title.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        title.setText("Sunday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        setBackground(OVER);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setBackground(DEFAULT);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        System.out.println("Click");
        File lf = new File(Diary8Desktop.CUser.getLogFolder(
                Diary8Desktop.DIARY.diaryPanel.selectedYear,
                Diary8Desktop.DIARY.diaryPanel.selectedMonth + 1,
                Diary8Desktop.DIARY.diaryPanel.selectedDate.getDate()).getAbsolutePath() + "/" + LogFile);
        System.out.println(lf.getAbsolutePath());
        String s = Diary8Desktop.CUser.read(lf);
        Diary8Desktop.DIARY.diaryPanel.dEditor2.setText(s);
        Diary8Desktop.DIARY.diaryPanel.jTextField1.setText(title.getText());
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setBackground(Color.BLACK);
        time.setForeground(Color.WHITE);
        title.setForeground(Color.WHITE);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setBackground(DEFAULT);
        time.setForeground(Color.BLACK);
        title.setForeground(Color.BLACK);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel time;
    public javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
