/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diary.app;

import diary.Diary8Desktop;
import diary.app.components.resources.Theme;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author Harsh
 */
public class Diary8View extends javax.swing.JFrame {

    Point mouseDownCompCoords;

    /**
     * Creates new form Diary8View
     */
    public Diary8View() {
        initComponents();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsConfiguration g = getGraphicsConfiguration();
        setBounds(0, 0,
                (int) ge.getMaximumWindowBounds().getWidth(),
                (int) ge.getMaximumWindowBounds().getHeight());
        setTheme(Diary8Desktop.THEMES.get(homePanel.selTheme));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaryPanel = new diary.app.components.DiaryPanel();
        peoplePanel = new diary.app.components.PeoplePanel();
        menuBar = new javax.swing.JPanel();
        rightSidePane = new javax.swing.JPanel();
        exitButton = new diary.app.controls.MButton();
        logoutButton = new diary.app.controls.MButton();
        minimiseButton = new diary.app.controls.MButton();
        homeButton = new diary.app.controls.MToggleButton();
        peopleButton = new diary.app.controls.MToggleButton();
        diaryButton = new diary.app.controls.MToggleButton();
        desk = new javax.swing.JPanel();
        homePanel = new diary.app.components.HomePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diary 8 Desktop");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Logo-150sq-blackback.png")).getImage());
        setUndecorated(true);
        setOpacity(0.95F);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(506, 50));

        rightSidePane.setOpaque(false);

        exitButton.setText("Exit");
        exitButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        exitButton.setMaximumSize(new java.awt.Dimension(100, 30));
        exitButton.setMinimumSize(new java.awt.Dimension(100, 30));
        exitButton.setPreferredSize(new java.awt.Dimension(100, 30));
        exitButton.setButtonColors(Color.white, new Color(255, 80, 80), Color.BLACK);
        exitButton.setTextColors(Color.BLACK, Color.WHITE, Color.WHITE);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        logoutButton.setText("Log Out");
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setMaximumSize(new java.awt.Dimension(100, 30));
        logoutButton.setMinimumSize(new java.awt.Dimension(100, 30));
        logoutButton.setPreferredSize(new java.awt.Dimension(100, 30));
        logoutButton.setButtonColors(Color.white, Diary8Colors.Red_L, Color.BLACK);
        logoutButton.setTextColors(Color.BLACK, Color.WHITE, Color.WHITE);

        minimiseButton.setText("-");
        minimiseButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimiseButton.setMaximumSize(new java.awt.Dimension(100, 30));
        minimiseButton.setMinimumSize(new java.awt.Dimension(100, 30));
        minimiseButton.setPreferredSize(new java.awt.Dimension(100, 30));
        minimiseButton.setButtonColors(Color.white, Diary8Colors.Blue_L, Color.BLACK);
        minimiseButton.setTextColors(Color.BLACK, Color.WHITE, Color.WHITE);
        minimiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightSidePaneLayout = new javax.swing.GroupLayout(rightSidePane);
        rightSidePane.setLayout(rightSidePaneLayout);
        rightSidePaneLayout.setHorizontalGroup(
            rightSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSidePaneLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(minimiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rightSidePaneLayout.setVerticalGroup(
            rightSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(minimiseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Logo-32sq-greytrans.png"))); // NOI18N
        homeButton.setSelected(true);
        homeButton.setText("");
        homeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Logo-32sq-greytrans.png"))); // NOI18N
        homeButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Logo-32sq-greytrans-invert.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        peopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Contacts_32x32.png"))); // NOI18N
        peopleButton.setText("");
        peopleButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Contacts_32x32.png"))); // NOI18N
        peopleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Contacts_32x32-invert.png"))); // NOI18N
        peopleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleButtonMouseClicked(evt);
            }
        });

        diaryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Library_32x32.png"))); // NOI18N
        diaryButton.setText("");
        diaryButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Library_32x32.png"))); // NOI18N
        diaryButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/diary/app/components/resources/Library_32x32-invert.png"))); // NOI18N
        diaryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(diaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(peopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightSidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSidePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peopleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diaryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        homeButton.setButtonColors(Color.WHITE, Color.BLACK);
        peopleButton.setButtonColors(Color.WHITE, Diary8Colors.Blue_L);
        diaryButton.setButtonColors(Color.WHITE, Diary8Colors.Green_L);

        desk.setBackground(new java.awt.Color(249, 249, 249));
        desk.setLayout(new java.awt.GridLayout(1, 1));
        desk.add(homePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        homeButton.setSelected(true);
        diaryButton.setSelected(false);
        peopleButton.setSelected(false);
        desk.removeAll();
        desk.add(homePanel);
        homePanel.revalidate();
        desk.revalidate();
        revalidate();
        homePanel.repaint();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void diaryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaryButtonMouseClicked
        // TODO add your handling code here:
        homeButton.setSelected(false);
        diaryButton.setSelected(true);
        peopleButton.setSelected(false);
        desk.removeAll();
        desk.add(diaryPanel);
        diaryPanel.revalidate();
        desk.revalidate();
        revalidate();
        diaryPanel.repaint();
    }//GEN-LAST:event_diaryButtonMouseClicked

    private void peopleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleButtonMouseClicked
        // TODO add your handling code here:
        homeButton.setSelected(false);
        diaryButton.setSelected(false);
        peopleButton.setSelected(true);
        desk.removeAll();
        desk.add(peoplePanel);
        peoplePanel.revalidate();
        desk.revalidate();
        revalidate();
        peoplePanel.repaint();
    }//GEN-LAST:event_peopleButtonMouseClicked

    private void minimiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimiseButtonActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimiseButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel desk;
    public diary.app.controls.MToggleButton diaryButton;
    public diary.app.components.DiaryPanel diaryPanel;
    public diary.app.controls.MButton exitButton;
    public diary.app.controls.MToggleButton homeButton;
    public diary.app.components.HomePanel homePanel;
    public diary.app.controls.MButton logoutButton;
    public javax.swing.JPanel menuBar;
    public diary.app.controls.MButton minimiseButton;
    public diary.app.controls.MToggleButton peopleButton;
    public diary.app.components.PeoplePanel peoplePanel;
    public javax.swing.JPanel rightSidePane;
    // End of variables declaration//GEN-END:variables

    private void setTheme(Theme get) {
        diaryButton.setButtonColors(Color.WHITE, get.BDEV1);
    }

    public interface Diary8Colors {

        public Color Red_L = new Color(255, 108, 108);
        public Color Blue_L = new Color(108, 108, 255);
        public Color Green_L = new Color(108, 255, 108);
    }
}
